name: ci workflow for python app test
on:
  push:
    branches:
      - "master"
# creating jobs 
jobs:
  ashu-python-app-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    steps:
      - name: checking python version on platform ${{ matrix.os }}
        run: python -V 
      
      - name: fetching git repo code to runners machine 
        uses: actions/checkout@v4
        
      - name: lets run python code on ${{ matrix.os }}
        run: python ashu.py 